data:
  max_length: 4096
  train_file: ./data/train.json
  val_file: ./data/val.json
inference:
  do_sample: true
  max_new_tokens: 2048
  temperature: 0.1
  top_p: 0.9
lora:
  bias: none
  loftq_config: null
  lora_alpha: 32
  lora_dropout: 0
  r: 32
  random_state: 42
  target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj
  use_gradient_checkpointing: unsloth
  use_rslora: false
model:
  dtype: bfloat16
  load_in_4bit: false
  max_seq_length: 4096
  name: ./models/Qwen/Qwen2___5-14B-Instruct
training:
  bf16: true
  fp16: false
  gradient_accumulation_steps: 8
  learning_rate: 0.0001
  logging_steps: 10
  lr_scheduler_type: linear
  num_train_epochs: 3
  optim: adamw_8bit
  output_dir: ./outputs
  per_device_train_batch_size: 1
  report_to: tensorboard
  save_steps: 100
  save_strategy: steps
  save_total_limit: 3
  seed: 42
  warmup_steps: 10
  weight_decay: 0.01
